
jobs:
  include:
    - stage: warm_cache
      script:
        - echo "foo" > foo.txt
      workspaces:
        create:
          name: ws1
          paths:
            - foo.txt
    - stage: warm_cache
      script:
        - echo "goo" > goo.txt
      workspaces:
        create:
          name: ws2
          paths:
            - goo.txt
    - stage: warm_cache
      script:
        - echo "toooo" > too.txt
      workspaces:
        create:
          name: ws3
          paths:
            - goo.txt
    - stage: use_cache
      workspaces:
        use: ws2
      script:
        - cat foo.txt || true
  
