
jobs:
  include:
    - stage: warm_cache
      script:
        - echo "foo" > foo.txt
      workspaces:
        create:
            - ws1
            - ws2
            - ws3
          paths:
            - foo.txt
    - stage: use_cache
      workspaces:
        use: 
          - ws1
          - ws2
          - ws3
      script:
        - cat goo.txt || true
  
