
jobs:
  include:
    - stage: warm_cache
      script:
        - echo "foo" > foo.txt
      workspaces:
        create:
          name: ws1
          name: ws2
          name: ws3
          paths:
            - foo.txt
    - stage: use_cache
      workspaces:
        use: 
          - ws1
          - ws2
          - ws3
      script:
        - cat goo.txt || true
  
