
jobs:
  include:
    - stage: Build and Test
      name: "Job A"
      script:
        - echo "Building Job A"
        - echo "Running tests for Job A"
      workspaces:
        create:
          name: workspace-a
          paths:
            - path/to/artifacts-A

    - name: "Job B"
      script:
        - echo "Building Job B"
        - echo "Running tests for Job B"
      workspaces:
        create:
          name: workspace-b
          paths:
            - path/to/artifacts-B

    - name: "Job C"
      script:
        - echo "Building Job C"
        - echo "Running tests for Job C"
      workspaces:
        create:
          name: workspace-c
          paths:
            - path/to/artifacts-C

    - stage: Deploy
      name: "Deploy"
      script:
        - echo "Deploying using artifacts from Job A and Job B"
      workspaces:
        use:
          - workspace-a
          - workspace-b


  
